# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will runh
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Setup DVC
        uses: iterative/setup-dvc@v1
      - name: Get data from DVC
        run: dvc pull
      - name: Setup python 3.8
        with:
          python-version: 3.8
        uses: actions/setup-python@v2
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r starter/requirements.txt
      - name: Run pytest
        working-directory: ./starter
        run: |
          pip install pytest
          python -m pytest .
      - name: Run flake8
        working-directory: ./starter
        run: |
          pip install flake8
          flake8 .
        
